name: IQDent
newname: INODent
title: "Oferte implant dentar"
description: "Oferte implant dentar pret ieftin. Bucuresti, Sector 3. Implanturi dentare la preturi rezonabile."
url: https://www.oferteimplantdentar.ro

color:
    primary: 2C3E50
    secondary: 18BC9C
    
contact:
    office:
        fb: http://facebook.com/dririnaalexandru
        gplus: 
        twitter: 
        tel: 0754 523 624
        url: https://www.inodent.ro
            
    one: 
        name: Dr. Irina Alexandru
        prefix: irina-
        tel: 0754 523 624
        img: /img/team/1.jpg
        fb: https://www.facebook.com/dririnaalexandru
        msg: https://www.facebook.com/messages/dririnaalexandru
        email: inodent.ro@gmail.com
        address: Bdul Octavian Goga Nr 21, Bucuresti


offer:
    expirydate: 30 Aprilie 2019
    extramonth: Septembrie 2018


permalink: none

map:
    key: AIzaSyBjpBjFh9xbRqw8jBS6vV4d53vlWpjDTpI

gems:
  - jekyll-feed
  - jekyll-sitemap
  
  

