name: IQDent
url: https://www.oferteimplantdentar.ro

color:
    primary: 2C3E50
    secondary: 18BC9C
    
contact:
    office:
        fb: http://facebook.com/dririnaalexandru
        gplus: 
        twitter: 
        tel: 
            
    one: 
        name: Dr. Irina Alexandru
        prefix: irina-
        tel: 0766 748 971
        img: img/team/1.jpg
        fb: https://www.facebook.com/dririnaalexandru
        msg: https://www.facebook.com/messages/dririnaalexandru
        email: alexandru.irina@yahoo.com
        address: Bdul Octavian Goga Nr 21, Bucuresti


offer:
    expirydate: 31 Decembrie 2016

permalink: none

gems:
  - jekyll-sitemap
  

